name: CI Build and Run

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
        with:
          version: 20.10.7  # Specify the desired Docker version

      - name: Build Docker image
        run: |
          docker build -t my_training_pipeline .

      - name: Run Python scripts in Docker image
        run: |
          # Run your Python scripts or commands within the Docker container
          docker container run my_training_pipeline python3 preprocessing.py
          docker container run my_training_pipeline python3 train.py
          docker container run my_training_pipeline python3 test.py

          # Add more script executions as needed
