name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build . -f Dockerfile -t my-image-name

      - name: Create and start Docker container
        run: |
          docker run --name my_training_pipeline -d my-image-name
      - name: Run Python scripts in Docker container
        run: |
          docker exec my_training_pipeline echo "[DEFAULT]
                    host = https://community.cloud.databricks.com/
                    username = micolp20022@gmail.com
                    password = Khanhvovan2002@
                    jobs-api-version = 2.0" > ~/.databrickscfg
          docker exec my_training_pipeline python3 preprocessing.py
          docker exec my_training_pipeline python3 train.py
          docker exec my_training_pipeline python3 test.py

      - name: Stop and remove Docker container
        run: |
          docker stop my_training_pipeline
          docker rm my_training_pipeline
